[package]
name = "s3_file_sync"
version = "0.1.0"
authors = ["vlad"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.3.9"
notify = { version = "5.0.0-pre.1", features = ["serde"] }
rusqlite = { version = "0.21.0", features = ["bundled", "chrono"] }
chrono = { version = "0.4", features = ["serde"] }
